---
- name: Configure policy {{ policy.key }}
  ini_file:
    path: /etc/sanoid/sanoid.conf
    section: "{{ policy.key }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: '0644'
  loop: "{{ policy.value | dict2items }}"
  loop_control:
    label: "[{{ policy.key }}] {{ item.key }} = {{ item.value }}"
