---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install python3-debian to support deb822_repository module
      apt:
        name: python3-debian
    - name: Install contrib repo
      deb822_repository:
        name: contrib
        types: deb
        uris: http://deb.debian.org/debian
        suites: "{{ ansible_distribution_release }}"
        components: contrib
      notify: Update apt cache
  handlers:
    - name: Update apt cache
      apt:
        update_cache: yes
